config/routes.rb
Rails.application.routes.draw do

  root to: 'save_the_dates#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :rooms
  resources :save_the_dates
  resources :saves
  get '/infos', to: "pages#infos"
  get '/confirmed', to: "save_the_dates#confirmed"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/save.rb
class Save < ApplicationRecord
  validates :name, presence: true
end

app/models/save_the_date.rb
class SaveTheDate < ApplicationRecord
  validates :name, presence: true
end

app/models/save_the_date2.rb
class SaveTheDate2 < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def infos
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
  end
end

app/controllers/save_the_dates_controller.rb
class SaveTheDatesController < ApplicationController
  def index
    @save_the_dates = SaveTheDate.all
    @saves = Save.all
  end

  def show
  end

  def new
    @save_the_date = SaveTheDate.new
  end

  def create
    @save_the_date = SaveTheDate.new(save_params)
    if @save_the_date.save
      redirect_to confirmed_path
    else
      render 'new'
    end
  end

  def edit
    @save_the_date = SaveTheDate.find(params[:id])
  end

  def update
    @save_the_date = SaveTheDate.find(params[:id])
    if @save_the_date.update(save_params)
      redirect_to save_the_dates_path
    else
      render 'update'
    end
  end

  def destroy
    @save_the_date = SaveTheDate.find(params[:id])
    @save_the_date.destroy
    redirect_to save_the_dates_path
  end

  def confirmed
  end

  private

  def save_params
    params.require(:save_the_date).permit(:name, :present, :mairie, :rien, :number_of_invites, :comment)
  end
end

app/controllers/save_the_datess_controller.rb
class SaveTheDatessController < ApplicationController
  def index
    @save_the_datesss = SaveTheDatess.all
  end

  def show
  end

  def new
    @save_the_datess = SaveTheDatess.new
  end

  def create
    @save_the_datess = SaveTheDatess.new(save_params)
    if @save_the_datess.save
      redirect_to confirmed_path
    else
      render 'new'
    end
  end

  def confirmed
  end

  private

  def save_params
    params.require(:save_the_datess).permit(:name, :present, :mairie, :rien, :number_of_invites, :comment )
  end
end

app/controllers/saves_controller.rb
class SavesController < ApplicationController
  def new
    @save = Save.new
  end

  def create
    @save = Save.new(save_params)
    if @save.save
      redirect_to confirmed_path
    else
      render 'new'
    end
  end

  def edit
    @save = Save.find(params[:id])
  end

  def update
    @save = Save.find(params[:id])
    if @save.update(save_params)
      redirect_to save_the_dates_path
    else
      render 'update'
    end
  end

  def destroy
    @save = Save.find(params[:id])
    @save.destroy
    redirect_to save_the_dates_path
  end

  private

  def save_params
    params.require(:save).permit(:name, :present, :mairie, :rien, :number_of_invites, :comment )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1519741497674-611481863552?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80);">
  <div class="container">
    <h1>Welcome to <strong>Laura and Cyril's wedding</strong> !</h1>
    <p>Bienvenue sur le site du mariage</p>
    <%= link_to "Bienvenue", new_save_the_date_path, class: 'btn btn-welcome' %>

  </div>
</div>

app/views/pages/infos.html.erb
<div class="row scroll text-center">
  <div class="savedate col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
    <%= cl_image_tag("https://res.cloudinary.com/dpcd0je1d/image/upload/v1574703225/lisa/page_presentation_mariage_bis_ezzske.jpg") %>
  </div>
  <div class="savedate col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">

    <%= cl_image_tag("https://res.cloudinary.com/dpcd0je1d/image/upload/v1574704489/lisa/PROGRAMME_MARIAGE_FLEURS_jvzefb.jpg") %>

  </div>
  <div class="savedate col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">

    <a href="mailto:hotel@beldicountryclub.com">
      <%= cl_image_tag("https://res.cloudinary.com/dpcd0je1d/image/upload/v1574704649/lisa/hebergements_pr6329.jpg ") %>
    </a>
  </div>
</div>

app/views/pages/programme.html.erb
<div class="row">
  <div class="savedate col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
    <%= cl_image_tag("https://res.cloudinary.com/dpcd0je1d/image/upload/v1574703225/lisa/page_presentation_mariage_bis_ezzske.jpg") %>
  </div>
  <div class="savedate col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">

    <%= cl_image_tag("https://res.cloudinary.com/dpcd0je1d/image/upload/v1574703226/lisa/programme_mariage_kdjasf.jpg") %>

  </div>
  <div class="savedate col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">


    <%= cl_image_tag("https://res.cloudinary.com/dpcd0je1d/image/upload/v1574703282/lisa/templett_3083276_2_1_o5garv.pdf") %>

  </div>
</div>

app/views/rooms/index.html.erb
<h1 class="text-center">Reservation de l'hôtel</h1>

<div class="cards">
  <% @rooms.each do |room| %>
  <%= link_to room_path(room) do %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1518568814500-bf0f8d125f46?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80)">
    <%= room.name %>
  </div>
  <% end %>
  <% end %>

</div>

app/views/rooms/show.html.erb
<br><br>
<h1><%=  @room.name%></h1>
<p>Pour : <%= @room.capacity %> personnes </p>
<p><%= @room.type_of_the_room %></p>
<p>Pour : <%= @room.number_of_days %> jours</p>

app/views/save_the_dates/confirmed.html.erb
<div class="message-confirmation col-12">
  <%= cl_image_tag("https://res.cloudinary.com/dpcd0je1d/image/upload/v1570629209/lisa/message_envoye%CC%81_templett_2676478_2_fi5d2k_1_brxwlp.jpg") %>
</div>

app/views/save_the_dates/edit.html.erb
<h1>MODIFIER <%= @save_the_date.name %> : </h1>

<%= simple_form_for @save_the_date do |f| %>


<%= f.input :name, label: "Nom et Prénom : " %>
<div class="row">
  <div class="col-sm">
    <%= f.input :present, label:"Oui, je serai présent(e) !", class: "checkbox", input_html: { id: "1" } %>
  </div>
  <div class="col-sm">
    <%= f.input :number_of_invites, default:0, label: "     | Nous serons : " , collection: [0, 1, 2, 3, 4, 5], input_html: { :style=> 'width: 25%;', :rows => 4}%>
  </div>
</div>
<%= f.input :mairie, label:"Non, mais je serai présent(e) au mariage civil à Paris", class: "checkbox", input_html: { id: "2" }  %>
<%= f.input :rien, label:"Je ne vais pas pouvoir mais je penserai à vous !", class: "checkbox", input_html: { id: "3" }  %>

<%= f.submit "ENVOYER", class: 'btn btn-send' %>
<% end %>

<%= link_to "Delete", save_the_date_path(@save_the_date),
method: :delete,
data: { confirm: "Are you sure?" }, class:"btn-del" %>



<script>

  const checkbox1 = document.getElementById("1");

  const checkbox2 = document.getElementById("2");

  const checkbox3 = document.getElementById("3");

  function handleChecked1() {

    checkbox2.checked = false;

    checkbox3.checked = false;

  }

  function handleChecked2() {

    checkbox1.checked = false;

    checkbox3.checked = false;

  }

  function handleChecked3() {

    checkbox1.checked = false;

    checkbox2.checked = false;

  }


  checkbox1.addEventListener('change', handleChecked1)
  checkbox2.addEventListener('change', handleChecked2)
  checkbox3.addEventListener('change', handleChecked3)

</script>

app/views/save_the_dates/index.html.erb
<div class="container">
  <h1>Ceux qui ont répondus</h1>
  <% a = 0 %>
  <% @save_the_dates.each do |s|  %>
  <% a += s.number_of_invites %>
  <% end %>



  <p>Groupe 3 jours :  <%= a %></p>



  <h2>GROUPE 3 JOURS</h2>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Nom</th>
        <th scope="col">👨‍👩‍👧‍👦</th>
        <th scope="col">🐪</th>
        <th scope="col">💒</th>
        <th scope="col">❌</th>
        <th scope="col">Petit mot 📋</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @save_the_dates.each do |answer| %>
      <tr>
        <th scope="row"><%= answer.name %></th>
        <td><%= answer.number_of_invites %></td>
        <td><%= answer.present ? "🐪" : "-" %></td>
        <td><%= answer.mairie ? "💒" : "-" %></td>
        <td><%= answer.rien ? "❌" : "-" %></td>
        <td><%= answer.comment %></td>
        <td> <%= link_to "Edit", edit_save_the_date_path(answer) %></td>
      </tr>
      <%end%>
    </tbody>
  </table>




  <h2>GROUPE 2 JOURS</h2>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Nom</th>
        <th scope="col">👨‍👩‍👧‍👦</th>
        <th scope="col">🐪</th>
        <th scope="col">💒</th>
        <th scope="col">❌</th>
        <th scope="col">Petit mot 📋</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @saves.each do |answer| %>
      <tr>
        <th scope="row"><%= answer.name %></th>
        <td><%= answer.number_of_invites %></td>
        <td><%= answer.present ? "🐪" : "-" %></td>
        <td><%= answer.mairie ? "💒" : "-" %></td>
        <td><%= answer.rien ? "❌" : "-" %></td>
        <td><%= answer.comment %></td>
        <td> <%= link_to "Edit", edit_safe_path(answer) %></td>
      </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/save_the_dates/new.html.erb
<div class="row pagesavedate">
  <div class="savedate col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
    <%= cl_image_tag("https://res.cloudinary.com/dpcd0je1d/image/upload/v1570642055/lisa/Unknown_u3rlgw.jpg") %>
  </div>
  <div class="justify-content-center align-items-center col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
    <div class="confirmation-presence">

      <h5>
      Confirmation de votre présence : </h5>
      <br>


      <%= simple_form_for @save_the_date do |f| %>
      <%= f.input :name, label: "Nom et Prénom : " %>

      <div class="row">
        <div class="col-sm">
          <%= f.input :present, label:"Oui, je serai présent(e) !", class: "checkbox", input_html: { id: "1" } %>
        </div>
        <div class="col-sm">
          <%= f.input :number_of_invites, default:0, label: "     | Nous serons : " , collection: [0, 1, 2, 3, 4, 5], input_html: {id: "4", :style=> 'width: 25%;', :rows => 4}%>
        </div>
      </div>
      <%= f.input :mairie, label:"Non, mais je serai présent(e) au mariage civil à Paris", class: "checkbox", input_html: { id: "2" }  %>
      <%= f.input :rien, label:"Je ne vais pas pouvoir mais je penserai à vous !", class: "checkbox", input_html: { id: "3" }  %>
      <%= f.input :comment, label: "Laissez nous un petit mot : ", :as => :text, input_html: { :style=> 'width: 100%;', :rows => 4} %>
      <%= f.submit "ENVOYER", class: 'btn btn-send' %>
      <% end %>


    </div>
  </div>
</div>



<script>

  const checkbox1 = document.getElementById("1");

  const checkbox2 = document.getElementById("2");

  const checkbox3 = document.getElementById("3");

  function handleChecked1() {

    checkbox2.checked = false;

    checkbox3.checked = false;

  }

  function handleChecked2() {

    checkbox1.checked = false;

    checkbox3.checked = false;

  }

  function handleChecked3() {

    checkbox1.checked = false;

    checkbox2.checked = false;

  }

  function unable() {
    if (checkbox2.checked) {
      document.getElementById("4").disabled = true;
    }
    else if (checkbox3.checked) {
      document.getElementById("4").disabled = true;
    }
    else {
      document.getElementById("4").disabled = false;
    }
  }


  checkbox1.addEventListener('change', handleChecked1)
  checkbox2.addEventListener('change', handleChecked2)
  checkbox3.addEventListener('change', handleChecked3)

  // checkbox1.addEventListener('change', unable)
  // checkbox2.addEventListener('change', unable)
  // checkbox3.addEventListener('change', unable)

</script>

app/views/save_the_datess/confirmed.html.erb
<div class="message-confirmation">
  <%= cl_image_tag("https://res.cloudinary.com/dzdqmawpj/image/upload/v1570466285/message%20envoy%C3%A9/templett_2676478_2_fi5d2k.jpg") %>
</div>

app/views/save_the_datess/index.html.erb
<h1> Groupe 2 : Ceux qui ont répondus</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Nom</th>
      <th scope="col">Nombre d'invités</th>
      <th scope="col">Présent à Marrakech</th>
      <th scope="col">Présent à la mairie</th>
      <th scope="col">Pas là du tout</th>
      <th scope="col">Petit mot</th>
    </tr>
  </thead>
  <tbody>
    <% @save_the_dates2.each do |answer| %>
    <tr>
      <th scope="row"><%= answer.name %></th>
      <td><%= answer.number_of_invites %></td>
      <td><%= "✅" if answer.present %></td>
      <td><%= "✅" if answer.mairie %></td>
      <td><%= "✅" if answer.rien %></td>
      <td><%= answer.comment %></td>

      <%  %>
      <td><%=  %></td>
    </tr>
    <%end%>
  </tbody>
</table>

app/views/save_the_datess/new.html.erb
<div class="row pagesavedate hid-overflow">
  <div class="savedate col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
    <%= cl_image_tag("https://res.cloudinary.com/dpcd0je1d/image/upload/v1570448228/lisa/save_hyhbqb.jpg") %>
  </div>
  <div class="justify-content-center align-items-center col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
    <div class="confirmation-presence">
      <br>

      <h5>
      Confirmation de votre presence:</h5>
      <br>


      <%= simple_form_for @save_the_date2 do |f| %>
      <%= f.input :name, label: "Nom et Prénom : " %>

      <div class="row">
        <div class="col-sm">
          <%= f.input :present, label:"Oui, je serai présent(e) !" %>
        </div>
        <div class="col-sm">
          <%= f.input :number_of_invites, default:0, label: "     | Nous serons :" , collection: [0, 1, 2, 3, 4, 5], input_html: { :style=> 'width: 25%;', :rows => 4}%>
        </div>
      </div>
      <%= f.input :mairie, label:"Non, mais je serai présent(e) au mariage civil à Paris" %>
      <%= f.input :rien, label:"Je ne vais pas pouvoir mais je penserai à vous !" %>
      <%= f.input :comment, label: "Laissez nous un petit mot : ", :as => :text, input_html: { :style=> 'width: 100%;', :rows => 4} %>
      <%= f.submit "ENVOYER", class: 'btn btn-send' %>
      <% end %>


    </div>
  </div>
</div>

app/views/saves/edit.html.erb
<h1>MODIFIER <%= @save.name %> : </h1>

<%= simple_form_for @save do |f| %>


<%= f.input :name, label: "Nom et Prénom : " %>
<div class="row">
  <div class="col-sm">
    <%= f.input :present, label:"Oui, je serai présent(e) !", class: "checkbox", input_html: { id: "1" } %>
  </div>
  <div class="col-sm">
    <%= f.input :number_of_invites, default:0, label: "     | Nous serons : " , collection: [0, 1, 2, 3, 4, 5], input_html: { :style=> 'width: 25%;', :rows => 4}%>
  </div>
</div>
<%= f.input :mairie, label:"Non, mais je serai présent(e) au mariage civil à Paris", class: "checkbox", input_html: { id: "2" }  %>
<%= f.input :rien, label:"Je ne vais pas pouvoir mais je penserai à vous !", class: "checkbox", input_html: { id: "3" }  %>

<%= f.submit "ENVOYER", class: 'btn btn-send' %>
<% end %>


<%= link_to "Delete", safe_path(@save),
method: :delete,
data: { confirm: "Are you sure?" }, class:"btn-del" %>


<script>

  const checkbox1 = document.getElementById("1");

  const checkbox2 = document.getElementById("2");

  const checkbox3 = document.getElementById("3");

  function handleChecked1() {

    checkbox2.checked = false;

    checkbox3.checked = false;

  }

  function handleChecked2() {

    checkbox1.checked = false;

    checkbox3.checked = false;

  }

  function handleChecked3() {

    checkbox1.checked = false;

    checkbox2.checked = false;

  }


  checkbox1.addEventListener('change', handleChecked1)
  checkbox2.addEventListener('change', handleChecked2)
  checkbox3.addEventListener('change', handleChecked3)

</script>

app/views/saves/new.html.erb
<div class="row pagesavedate">
  <div class="savedate col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
    <%= cl_image_tag("https://res.cloudinary.com/dpcd0je1d/image/upload/v1570896865/lisa/les_2_save_the_date_save_the_date_16-18_Juin_chwp6d_lrfnu6.jpg") %>
  </div>
  <div class="justify-content-center align-items-center col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
    <div class="confirmation-presence">

      <h5>
      Confirmation de votre présence : </h5>
      <br>


      <%= simple_form_for @save do |f| %>
      <%= f.input :name, label: "Nom et Prénom : " %>

      <div class="row">
        <div class="col-sm">
          <%= f.input :present, label:"Oui, je serai présent(e) !", class: "checkbox", input_html: { id: "1" } %>
        </div>
      </div>
      <%= f.input :mairie, label:"Non, mais je serai présent(e) au mariage civil à Paris le 4 juin", class: "checkbox", input_html: { id: "2" }  %>
      <%= f.input :rien, label:"Je ne vais pas pouvoir mais je penserai à vous !", class: "checkbox", input_html: { id: "3" }  %>
      <%= f.input :comment, label: "Laissez nous un petit mot : ", :as => :text, input_html: { :style=> 'width: 100%;', :rows => 4} %>
      <%= f.submit "ENVOYER", class: 'btn btn-send' %>
      <% end %>


    </div>
  </div>
</div>



<script>

  const checkbox1 = document.getElementById("1");

  const checkbox2 = document.getElementById("2");

  const checkbox3 = document.getElementById("3");

  function handleChecked1() {

    checkbox2.checked = false;

    checkbox3.checked = false;

  }

  function handleChecked2() {

    checkbox1.checked = false;

    checkbox3.checked = false;

  }

  function handleChecked3() {

    checkbox1.checked = false;

    checkbox2.checked = false;

  }

  function unable() {
    if (checkbox2.checked) {
      document.getElementById("4").disabled = true;
    }
    else if (checkbox3.checked) {
      document.getElementById("4").disabled = true;
    }
    else {
      document.getElementById("4").disabled = false;
    }
  }


  checkbox1.addEventListener('change', handleChecked1)
  checkbox2.addEventListener('change', handleChecked2)
  checkbox3.addEventListener('change', handleChecked3)

  // checkbox1.addEventListener('change', unable)
  // checkbox2.addEventListener('change', unable)
  // checkbox3.addEventListener('change', unable)

</script>